# Generated by Django 5.0.14 on 2025-04-09 16:54

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, validators=[posts.models.validate_creation_date], verbose_name='Дата создания'),
        ),
    ]
