# Generated by Django 5.0.14 on 2025-04-21 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Имя родителя')),
                ('origin', models.CharField(help_text='Например, Асгард, Земля', max_length=200, verbose_name='Происхождение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigrees', to='posts.post', verbose_name='Персонаж (Пост)')),
            ],
            options={
                'verbose_name': 'Родословная',
                'verbose_name_plural': 'Родословные',
            },
        ),
    ]
